--------------------------------------------------------
--  DDL for Table SALGRADE
--------------------------------------------------------

  CREATE TABLE "TEST"."SALGRADE" 
   (	"GRADE" NUMBER, 
	"LOSAL" NUMBER, 
	"HISAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS1" ;
REM INSERTING into TEST.SALGRADE
SET DEFINE OFF;
Insert into TEST.SALGRADE (GRADE,LOSAL,HISAL) values (1,700,1200);
Insert into TEST.SALGRADE (GRADE,LOSAL,HISAL) values (2,1201,1400);
Insert into TEST.SALGRADE (GRADE,LOSAL,HISAL) values (3,1401,2000);
Insert into TEST.SALGRADE (GRADE,LOSAL,HISAL) values (4,2001,3000);
Insert into TEST.SALGRADE (GRADE,LOSAL,HISAL) values (5,3001,9999);
--------------------------------------------------------
--  DDL for Index SALG_GRADE_IX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SALG_GRADE_IX" ON "TEST"."SALGRADE" ("GRADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS1" ;
--------------------------------------------------------
--  Constraints for Table SALGRADE
--------------------------------------------------------

  ALTER TABLE "TEST"."SALGRADE" ADD CONSTRAINT "SALG_PK" PRIMARY KEY ("GRADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS1"  ENABLE;
