SELECT P.PRODUCT_ID, P.PRODUCT_NAME, 
       W.CUST_ID, C.CUST_LNAME AS NAME, W.UNIT_PRICE, W.RGST_DATE
FROM PRODUCTS P 
JOIN WISHLIST W
  ON P.PRODUCT_ID = W.PRODUCT_ID
JOIN CUSTOMERS C
  ON W.CUST_ID = C.CUST_ID;
  
  
SELECT E.EMPLOYEE_ID, E.LAST_NAME AS "Name", 
       J.JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J
  ON E.JOB_ID = J.JOB_ID;
  
  
SELECT S.PROD_ID, S.CUST_ID,
       P.PROMO_NAME, P.PROMO_BEGIN_DATE
FROM SALES S
JOIN PROMOTIONS P
  ON S.PROMO_ID = P.PROMO_ID
WHERE P.PROMO_BEGIN_DATE <> '9999/01/01';


SELECT C.CUST_ID, C.CUST_LNAME AS NAME, C.PHONE_NUMBER,
       B.REASON_CODE
FROM CUSTOMERS C
JOIN BLACKLIST B
  ON C.CUST_ID = B. CUST_ID;
  
  
SELECT L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM LOCATIONS L
JOIN COUNTRIES C
  ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R
  ON C.REGION_ID = R.REGION_ID;
  
  
SELECT O.ORDER_ID, E.LAST_NAME AS RESPONSIBLES, D.DEPARTMENT_NAME
FROM ORDERS O
JOIN EMPLOYEES E
  ON O.SALES_REP_ID = E.EMPLOYEE_ID
JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
  
  
SELECT DISTINCT I.ORDER_ID, O.ORDER_DATE, O.CUST_ID
FROM ORDER_ITEMS I
JOIN ORDERS O
  ON I.ORDER_ID = O.ORDER_ID;
  

SELECT E.LAST_NAME AS QUIT_EMP, H.START_DATE, H.END_DATE
FROM EMPLOYEES E
JOIN JOB_HISTORY H
  ON E.EMPLOYEE_ID = H.EMPLOYEE_ID;
  
  
SELECT D.DNAME, E.ENAME
FROM DEPT D
JOIN EMP E
  ON D.DEPTNO = E.DEPTNO;
  
  
SELECT DISTINCT C.ORDER_ID, C.CANCEL_STATUS, C.CANCEL_DATE, A.ORDER_DATE
FROM ORDER_CANCEL C
JOIN ORDER_ITEMS O
  ON C.ORDER_ID = O.ORDER_ID
JOIN ORDERS A
  ON O.ORDER_ID = A.ORDER_ID;
