-- 직원 급여의 누적 계산
SELECT EMPNO, ENAME, SAL, 
       ( SELECT SUM(SAL)
         FROM EMP
         WHERE EMPNO <= E.EMPNO ) AS ACC_SAL
FROM EMP E
ORDER BY EMPNO;

SELECT EMPNO, ENAME, 
       SUM(SAL) OVER(ORDER BY EMPNO)
FROM EMP;


-- 부서별 급여의 합 계산
SELECT EMPNO, ENAME, 
       SUM(SAL) OVER(PARTITION BY DEPTNO)
FROM EMP;


-- 고객 이력이 2건 이상인 고객의 정보 출력
SELECT *
FROM ( SELECT D.*, COUNT(*) OVER(PARTITION BY CUST_ID) AS CNT 
       FROM DORMANT_HIST D )
WHERE CNT >= 2;