-- NEXTVAL : 자동으로 다음 순번 입력
-- 다른 사람의 DB에 접속할 때는 '사용자.DB명'으로 접속
INSERT INTO TEST.STUDENT
VALUES (TEST.STDID_SQ.NEXTVAL, '최광삼');


-- SELECT 문
SELECT *
FROM TEST.STUDENT
ORDER BY 1;

SELECT *
FROM TEST.SURVEY
ORDER BY 1;

SELECT *
FROM TEST.TCMT;

-- 수강생 정보와 설문조사 결과 종합
SELECT S.STDID, S.NAME, V.OX, V.MENU
FROM TEST.STUDENT S JOIN TEST.SURVEY V
  ON S.STDID = V.STDID
ORDER BY 1;

-- 설문을 2회 이상 입력한 수강생
SELECT S.NAME, COUNT(S.NAME) AS INSERT_ERROR
FROM TEST.SURVEY V JOIN TEST.STUDENT S
  ON V.STDID = S.STDID
GROUP BY S.NAME
HAVING COUNT(S.NAME) >= 2;

-- 메뉴 선택 횟수
SELECT MENU, COUNT(*)
FROM TEST.SURVEY
GROUP BY MENU
ORDER BY 2 DESC;

-- 가장 많이 선택된 메뉴
SELECT MENU, PICKS
FROM ( SELECT MENU, COUNT(MENU) AS PICKS
       FROM TEST.SURVEY
       GROUP BY MENU )
WHERE PICKS IN ( SELECT MAX(COUNT(MENU))
                 FROM TEST.SURVEY
                 GROUP BY MENU );

-- 수강생 정보와 하고 싶은 말 종합1
SELECT S.STDID, S.NAME, T.CMT
FROM TEST.STUDENT S LEFT JOIN TEST.TCMT T
  ON S.STDID = T.STDID
ORDER BY 1;

-- 수강생 정보와 하고 싶은 말 종합2
SELECT STDID, NULL
FROM TEST.STUDENT
UNION ALL
SELECT STDID, CMT
FROM TEST.TCMT;


-- INSERT 문
INSERT INTO TEST.SURVEY
VALUES (20, 'X', NULL);

INSERT INTO TEST.TCMT
VALUES (NULL , NULL);


-- UPDATE 문
UPDATE TEST.SURVEY
SET MENU = NULL
WHERE STDID = 20;

COMMIT;
ROLLBACK;
