DECLARE 
  P_EMPNO   EMP.EMPNO%TYPE := 1111 ; 
  P_ENAME   EMP.ENAME%TYPE := 'RYU'; 
  P_SAL     EMP.SAL%TYPE   := 1000; 
  P_DEPTNO  EMP.DEPTNO%TYPE := 10; 

  V_CNT     NUMBER ; 
BEGIN 
  INSERT INTO EMP (EMPNO,ENAME,SAL,DEPTNO) 
  VALUES (P_EMPNO, P_ENAME, P_SAL, P_DEPTNO) ;
 
  SELECT COUNT(*) INTO V_CNT 
  FROM EMP_SUM
  WHERE DEPTNO = P_DEPTNO 
    AND ROWNUM = 1 ; 
  
  IF V_CNT > 0 THEN 
    UPDATE EMP_SUM 
	SET SUM_SAL = SUM_SAL + P_SAL 
	WHERE DEPTNO = P_DEPTNO ; 
  ELSE 
    INSERT INTO EMP_SUM 
	VALUES (P_DEPTNO, P_SAL) ; 
  END IF ;
END ; 
/

SELECT * FROM EMP WHERE EMPNO = 1111 ;
SELECT * FROM EMP_SUM ;
ROLLBACK ;

--------------------------------------------------

DECLARE 
  P_EMPNO   EMP.EMPNO%TYPE := 7788 ; 
  P_SAL     EMP.SAL%TYPE   := 1000; 

  REC_EMP   EMP%ROWTYPE ; 
BEGIN 
  SELECT * INTO REC_EMP 
  FROM EMP 
  WHERE EMPNO = P_EMPNO ; 
  
  UPDATE EMP 
  SET SAL = P_SAL 
  WHERE EMPNO = P_EMPNO ;

  UPDATE EMP_SUM 
  SET SUM_SAL = SUM_SAL + (P_SAL - REC_EMP.SAL)
  WHERE DEPTNO = REC_EMP.DEPTNO ; 

END ; 
/

SELECT * FROM EMP_SUM ;
ROLLBACK; 

--------------------------------------------------

DECLARE 
  P_EMPNO   EMP.EMPNO%TYPE := 7788 ; 
  REC_EMP   EMP%ROWTYPE ; 
BEGIN 
  SELECT * INTO REC_EMP 
  FROM EMP 
  WHERE EMPNO = P_EMPNO ; 
  
  DELETE EMP 
  WHERE EMPNO = P_EMPNO ;

  UPDATE EMP_SUM 
  SET SUM_SAL = SUM_SAL - REC_EMP.SAL
  WHERE DEPTNO = REC_EMP.DEPTNO ; 

END ; 
/

--------------------------------------------------

SELECT * FROM EMP_SUM ;
ROLLBACK;
