-- PRACTICE 1
CREATE TABLE DEPT2
( ID   NUMBER(7) CONSTRAINT DEPT2_PK PRIMARY KEY,
  NAME VARCHAR2(25) );
  
DESC DEPT2;


-- PRCATICE 2
CREATE TABLE EMP2
( ID         NUMBER(7),
  LAST_NAME  VARCHAR2(25),
  FIRST_NAME VARCHAR2(25),
  DEPT_ID    NUMBER(7)
             CONSTRAINT EMP2_FK REFERENCES DEPT2(ID) );

DESC EMP2;


-- PRACTICE 3
ALTER TABLE EMP2
ADD (COMMISSION  NUMBER(2, 2));


-- PRACTICE 4
ALTER TABLE EMP2
MODIFY (LAST_NAME  VARCHAR2(50));


-- PRACTICE 5
ALTER TABLE EMP2
DROP (FIRST_NAME);


-- PRACTICE 6
ALTER TABLE EMP2
SET UNUSED (DEPT_ID);


-- PRACTICE 7
ALTER TABLE EMP2
DROP UNUSED COLUMNS;


-- PRACTICE 8
CREATE TABLE EMPLOYEES2
AS
( SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, 
         SALARY, DEPARTMENT_ID AS DEPT_ID
  FROM EMPLOYEES );
  
DESC EMPLOYEES2;


-- PRACTICE 9
ALTER TABLE EMPLOYEES2 READ ONLY;


-- PRACTICE 10, 11
ALTER TABLE EMPLOYEES2 READ WRITE;

ALTER TABLE EMPLOYEES2
ADD JOB_ID VARCHAR2(9);


-- PRACTICE 12
DROP TABLE EMP2;
DROP TABLE DEPT2;
DROP TABLE EMPLOYEES2;