-- PRACTICE 1
CREATE TABLE MY_EMPLOYEE
( ID NUMBER(4) CONSTRAINT MY_EMPLOYEE_ID_PK PRIMARY KEY,
  LAST_NAME VARCHAR2(25),
  FIRST_NAME VARCHAR2(25),
  USERID VARCHAR2(8),
  SALARY NUMBER(9, 2) );


-- PRACTICE 2
DESC MY_EMPLOYEE;


-- PRACTICE 3
INSERT INTO MY_EMPLOYEE
VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);


-- PRACTICE 4
INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);


-- PRACTICE 5/8/12/14/17/20/22
SELECT *
FROM MY_EMPLOYEE;


-- PRACTICE 6/7/16
INSERT INTO MY_EMPLOYEE
VALUES (&ID, '&LAST_NAME', '&FIRST_NAME', '&USERID', &SALARY);


-- PRACTICE 9/15/23
COMMIT;


-- PRACTICE 10
UPDATE MY_EMPLOYEE
SET LAST_NAME = 'Drexler'
WHERE ID = 3;


-- PRACTICE 11
UPDATE MY_EMPLOYEE
SET SALARY = 1000
WHERE SALARY < 900;


-- PRACTICE 13
DELETE 
FROM MY_EMPLOYEE
WHERE LAST_NAME = 'Dancs';


-- PRACTICE 18
SAVEPOINT BACKUP1;


-- PRACTICE 19
DELETE MY_EMPLOYEE;


-- PRACTICE 21
ROLLBACK TO BACKUP1;


-- PRACTICE 24/25
INSERT INTO MY_EMPLOYEE
VALUES (&ID, '&&LAST_NAME', '&&FIRST_NAME',
        LOWER(SUBSTR('&FIRST_NAME', 1, 1) || SUBSTR('&LAST_NAME', 1, 7)), 
        &SALARY);
        
UNDEFINE LAST_NAME;
UNDEFINE FIRST_NAME;


-- PRACTICE 26
SELECT *
FROM MY_EMPLOYEE
WHERE ID = 6;