-- PRACTICE 1
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';


-- PRACTICE 2
SELECT COUNTRY_ID, COUNTRY_NAME
FROM COUNTRIES
MINUS
SELECT L.COUNTRY_ID, C.COUNTRY_NAME
FROM LOCATIONS L JOIN COUNTRIES C
  ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN DEPARTMENTS D
  ON D.LOCATION_ID = L.LOCATION_ID;


-- PRACTICE 3
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
UNION
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;


-- PRACTICE 4
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP'
INTERSECT
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;


-- PRACTICE 5
SELECT LAST_NAME, DEPARTMENT_ID, NULL AS DEPT_NAME
FROM EMPLOYEES
UNION
SELECT NULL, DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;
