-- PRACTICE 1
SELECT L.LOCATION_ID, L.STREET_ADDRESS, L.CITY, L.STATE_PROVINCE, C.COUNTRY_NAME
FROM LOCATIONS L NATURAL JOIN COUNTRIES C
ORDER BY L.LOCATION_ID;


-- PRACTICE 2
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY E.LAST_NAME;


-- PRACTICE 3
SELECT E.LAST_NAME, E.JOB_ID,
       E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D 
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
  ON D.LOCATION_ID = L.LOCATION_ID
WHERE UPPER(L.CITY) = 'TORONTO';


-- PRACTICE 4
SELECT E.LAST_NAME AS "Employee", E.EMPLOYEE_ID AS "EMP#",
       M.LAST_NAME AS "Manager", M.EMPLOYEE_ID AS "Mgr#"
FROM EMPLOYEES E JOIN EMPLOYEES M
  ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY M.LAST_NAME, E.EMPLOYEE_ID DESC;


-- PRACTICE 5
SELECT E.LAST_NAME AS "Employee", E.EMPLOYEE_ID AS "EMP#",
       M.LAST_NAME AS "Manager", M.EMPLOYEE_ID AS "Mgr#"
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
  ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY 2;


-- PRACTICE 6
SELECT E.DEPARTMENT_ID AS DEPARTMENT,
       E.LAST_NAME AS EMPLOYEE, C.LAST_NAME AS COLLEAGUE
FROM EMPLOYEES E JOIN EMPLOYEES C
  ON E.DEPARTMENT_ID = C.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID <> C.EMPLOYEE_ID
ORDER BY E.DEPARTMENT_ID, E.LAST_NAME;


-- PRACTICE 7
DESC JOB_GRADES;

SELECT E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_NAME, E.SALARY,
       J.GRADE_LEVEL
FROM EMPLOYEES E JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOB_GRADES J
  ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;


-- PRACTICE 8
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E JOIN EMPLOYEES D
  ON UPPER(D.LAST_NAME) = 'DAVIES' AND E.HIRE_DATE > D.HIRE_DATE;


-- PRACTICE 9
SELECT E.LAST_NAME, E.HIRE_DATE, M.LAST_NAME, M.HIRE_DATE
FROM EMPLOYEES E JOIN EMPLOYEES M
  ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.HIRE_DATE < M.HIRE_DATE;