-- PRACTICE 1
CREATE OR REPLACE VIEW EMPLOYEES_VU
AS ( SELECT EMPLOYEE_ID, LAST_NAME AS EMPLOYEE, DEPARTMENT_ID
     FROM EMPLOYEES );


-- PRACTICE 2
SELECT *
FROM EMPLOYEES_VU;


-- PRACTICE 3
SELECT EMPLOYEE, DEPARTMENT_ID
FROM EMPLOYEES_VU;


-- PRACTICE 4
CREATE OR REPLACE VIEW DEPT80
AS  SELECT EMPLOYEE_ID AS EMPNO,
            LAST_NAME AS EMPLOYEE,
            DEPARTMENT_ID AS DEPTNO
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 80
    WITH CHECK OPTION CONSTRAINT EMP_DEPT_80 ;


-- PRACTICE 5
DESC DEPT80;
SELECT * FROM DEPT80;


-- PRACTICE 6
UPDATE DEPT80
SET DEPTNO = 50
WHERE UPPER(EMPLOYEE) = 'ABEL';


-- PRACTICE 7
CREATE VIEW dept50 AS   
   SELECT   employee_id empno, last_name employee,
            department_id deptno
   FROM     employees
   WHERE    department_id = 50
   WITH CHECK OPTION CONSTRAINT emp_dept_50;

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;


-- PRACTICE 8
DROP VIEW EMPLOYEES_VU;
DROP VIEW DEPT80;
DROP VIEW DEPT50;