-- PRACTICE 1
SELECT TABLE_NAME
FROM USER_TABLES;


-- PRACTICE 2
SELECT TABLE_NAME, OWNER
FROM ALL_TABLES
WHERE OWNER <> 'TEST';


-- PRACTICE 3
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, 
       DATA_PRECISION AS PRECISION, DATA_SCALE AS SCALE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('&TABLE_NAME');


-- PRACTICE 4
SELECT C.COLUMN_NAME, S.CONSTRAINT_NAME, S.CONSTRAINT_TYPE,
       S.SEARCH_CONDITION, S.STATUS
FROM USER_CONSTRAINTS S JOIN USER_CONS_COLUMNS C
  ON S.TABLE_NAME = C.TABLE_NAME 
AND S.CONSTRAINT_NAME = C.CONSTRAINT_NAME
AND S.TABLE_NAME = UPPER('&TABLE_NAME');


-- PRACTICE 5
COMMENT ON TABLE DEPARTMENTS IS
'Company department information including name, code, and location.';

SELECT COMMENTS
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME = 'DEPARTMENTS';


-- PRACTICE 6
DROP TABLE DEPT2 PURGE;
DROP TABLE EMP2 PURGE;

CREATE TABLE DEPT2
AS ( SELECT * FROM EMP );
CREATE TABLE EMP2
AS ( SELECT * FROM EMP );


-- PRACTICE 7
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN ('DEPT2', 'EMP2');


-- PRACTICE 8
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT2', 'EMP2');


-- PRACTICE 9
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('DEPT2', 'EMP2');