-- PRACTICE 1
DROP TABLE DEPT2 PURGE;
DESC DEPT2;

CREATE TABLE DEPT2
( ID NUMBER(7) CONSTRAINTS DEPT_ID_PK PRIMARY KEY,
  NAME VARCHAR2(25) );


-- PRACTICE 2
CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
INCREMENT BY 10
MAXVALUE 1000;


-- PRACTICE 3
INSERT INTO DEPT2
VALUES ( DEPT_ID_SEQ.NEXTVAL, 'EDUCATION' );
INSERT INTO DEPT2
VALUES ( DEPT_ID_SEQ.NEXTVAL, 'ADMINISTRATION');


-- PRACTICE 4
SELECT SEQUENCE_NAME, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES;


-- PRACITCE 5
CREATE SYNONYM EMP1 FOR EMPLOYEES;
SELECT * FROM USER_SYNONYMS;


-- PRACTICE 6
DROP SYNONYM EMP1;


-- PRACITCE 7
CREATE INDEX DEPT_NAME_IDX ON DEPT2(NAME);


-- PRACTICE 8
CREATE TABLE SALES_DEPT
( TEAM_ID NUMBER(3) PRIMARY KEY 
          USING INDEX (CREATE INDEX SALES_PK_IDX ON SALES_DEPT(TEAM_ID)),
  LOCATION VARCHAR2(30) );

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME = 'SALES_DEPT';


-- PRACTICE 9
DROP TABLE DEPT2;
DROP TABLE SALES_DEPT;
DROP SEQUENCE DEPT_ID_SEQ;