-- PRACTICE 1~3
/*
1. 맞음
2. 틀림
3. 맞음
*/


-- PRACTICE 4
SELECT ROUND(MAX(SALARY), 0), ROUND(MIN(SALARY), 0), 
       ROUND(SUM(SALARY), 0), ROUND(AVG(SALARY), 0)
FROM EMPLOYEES;


-- PRACTICE 5
SELECT JOB_ID, ROUND(MAX(SALARY), 0), ROUND(MIN(SALARY), 0), 
               ROUND(SUM(SALARY), 0), ROUND(AVG(SALARY), 0)
FROM EMPLOYEES
GROUP BY JOB_ID;


-- PRACTICE 6
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
WHERE JOB_ID = '&FIND_JOB'
GROUP BY JOB_ID;


-- PRACTICE 7
SELECT COUNT(DISTINCT MANAGER_ID) AS "Number of Managers"
FROM EMPLOYEES;


-- PRACTICE 8
SELECT MAX(SALARY) - MIN(SALARY) AS "DIFFERENCE"
FROM EMPLOYEES;


-- PRACTICE 9
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000
ORDER BY MIN(SALARY) DESC;


-- PRACTICE 10
SELECT COUNT(*) AS TOTAL,
       SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 2005, 1, 0)) AS "2005",
       SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 2006, 1, 0)) AS "2006",
       SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 2007, 1, 0)) AS "2007",
       SUM(DECODE(TO_CHAR(HIRE_DATE, 'YYYY'), 2008, 1, 0)) AS "2008"
FROM EMPLOYEES;


-- PRACTICE 11
SELECT JOB_ID AS "JOB",
       SUM(DECODE(DEPARTMENT_ID, 20, SALARY)) AS "Dept 20",
       SUM(DECODE(DEPARTMENT_ID, 50, SALARY)) AS "Dept 50",
       SUM(DECODE(DEPARTMENT_ID, 80, SALARY)) AS "Dept 80",
       SUM(DECODE(DEPARTMENT_ID, 90, SALARY)) AS "Dept 90",
       SUM(SALARY) AS "Total"
FROM EMPLOYEES
GROUP BY JOB_ID;
