-- PRACTICE 1
DECLARE
    V_ENAME    EMPLOYEES.LAST_NAME%TYPE;
    V_EMP_SAL  EMPLOYEES.SALARY%TYPE := 6000;
BEGIN
    SELECT LAST_NAME INTO V_ENAME
    FROM EMPLOYEES
    WHERE SALARY = V_EMP_SAL;
    
    INSERT INTO MESSAGES (RESULTS)
    VALUES (V_ENAME || ' - ' || V_EMP_SAL);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO MESSAGES (RESULTS)
        VALUES ('NO EMPLOYEES WITH A SALARY OF ' || TO_CHAR(V_EMP_SAL));
    
    WHEN TOO_MANY_ROWS THEN
        INSERT INTO MESSAGES (RESULTS)
        VALUES ('MORE THAN ONE EMPLOYEE WITH A SALARY OF ' || TO_CHAR(V_EMP_SAL));
    
    WHEN OTHERS THEN
        INSERT INTO MESSAGES (RESULTS)
        VALUES ('SOME OTHER ERROR OCCURED.');
END;
/

SELECT * FROM MESSAGES;


-- PRACTICE 2
DECLARE
    E_CHILDRECORD_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_CHILDRECORD_EXISTS, -02292);
BEGIN
    DBMS_OUTPUT.PUT_LINE(' Deleting department 40........');
    
    DELETE FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = 40;
EXCEPTION
    WHEN E_CHILDRECORD_EXISTS THEN
    DBMS_OUTPUT.PUT_LINE('Cannot delete this department. There are 
                          employees in this department (child records exist.)');
END;
/