/* 
PRACTICE 1
利钦 : a, b, e, g, h
何利钦 : c, d, f


PRACTICE 2
利钦 : a, d
何利棱 : b, c


PRACTICE 3
翠 : a

*/


-- PRACTICE 4
DECLARE
    V_TODAY     DATE := SYSDATE;
    V_TOMORROW  V_TODAY%TYPE;
BEGIN
    V_TOMORROW := V_TODAY + 1;
    DBMS_OUTPUT.PUT_LINE('Hello World');
    DBMS_OUTPUT.PUT_LINE('TODAY IS : ' || V_TODAY);
    DBMS_OUTPUT.PUT_LINE('TOMORROW IS : ' || V_TOMORROW);
END;
/


-- PRACTICE 5
DECLARE
    V_TODAY     DATE := SYSDATE;
    V_TOMORROW  V_TODAY%TYPE;
    B_BASIC_PERCENT NUMBER;
    B_PF_PERCENT NUMBER;
BEGIN
    V_TOMORROW := V_TODAY + 1;
    DBMS_OUTPUT.PUT_LINE('Hello World');
    DBMS_OUTPUT.PUT_LINE('TODAY IS : ' || V_TODAY);
    DBMS_OUTPUT.PUT_LINE('TOMORROW IS : ' || V_TOMORROW);
    :B_BASIC_PERCENT := 45;
    :B_PF_PERCENT := 12;
END;
/

PRINT B_BASIC_PERCENT;
PRINT B_PF_PERCENT;