-- PRACTICE 1
BEGIN
FOR i IN 1..10 LOOP
    IF i = 6 OR i = 8 THEN
        CONTINUE;
    ELSE
        INSERT INTO MESSAGES (RESULTS)
        VALUES (i);
    END IF;
END LOOP;
COMMIT;
END;
/

SELECT * FROM MESSAGES;


-- PRACTICE 2
DECLARE
    V_EMPNO     EMP.EMPLOYEE_ID%TYPE := 76;
    V_ASTERISK  EMP.STARS%TYPE := NULL;
    V_SAL       EMP.SALARY%TYPE;
BEGIN
    SELECT NVL(ROUND(SALARY/1000), 0) INTO V_SAL
    FROM EMP
    WHERE EMPLOYEE_ID = V_EMPNO;
    
    FOR i IN 1..V_SAL
        LOOP
        V_ASTERISK := V_ASTERISK || '*';
    END LOOP;
    
    UPDATE EMP
    SET STARS = V_ASTERISK
    WHERE EMPLOYEE_ID = V_EMPNO;
END;
/

SELECT EMPLOYEE_ID, SALARY, STARS
FROM EMP
WHERE EMPLOYEE_ID = 176;