/*
PRACTICE 1
a : 2 (NUMBER)
b : Western Europe (VARCHAR2)
c : 601 (NUMBER)
d : Product 10012 is in stock (VARCHAR2)
e : ERROR


PRACTICE 2
a : 201 (NUMBER)
b : Unisports (VARCHAR2)
c : GOOD (VARCHAR2)
d : Womansport (VARCHAR2)
e : ERROR
f : EXCELLENT (VARCHAR2)
*/

-- PRACTICE 3
SET SERVEROUTPUT ON;

DECLARE
    V_BASIC_PERCENT NUMBER := 45;
    V_PF_PERCENT NUMBER := 12;
    V_FNAME VARCHAR2(15);
    V_EMP_SAL NUMBER(10);
BEGIN
    SELECT FIRST_NAME, SALARY INTO V_FNAME, V_EMP_SAL
    FROM EMPLOYEES WHERE EMPLOYEE_ID = 107;
    
    DBMS_OUTPUT.PUT_LINE('Hello ' || V_FNAME);
    DBMS_OUTPUT.PUT_LINE('YOUR SALARY IS : ' || V_EMP_SAL);
    DBMS_OUTPUT.PUT_LINE('YOUR CONTRIBUTION TOWARDS PF: ' ||
                          V_EMP_SAL*V_BASIC_PERCENT/100*V_PF_PERCENT/100);
END;
/