-- PRACTICE 1
DECLARE
    V_MAX_DEPTNO NUMBER;
BEGIN
    INCERT MAX(DEPARTMENT_ID) INTO V_MAX_DEPTNO
    FROM DEPARTMENTS;
    
    DBMS_OUTPUT.PUT_LINE('The Maximun Department_ID is : ' || V_MAX_DEPTNO);
END;
/


-- PRACTICE 2
DECLARE
    V_MAX_DEPTNO  NUMBER;
    V_DEPT_NAME   DEPARTMENTS.DEPARTMENT_NAME%TYPE := 'Education';
    V_DEPT_ID     NUMBER;
BEGIN
    SELECT MAX(DEPARTMENT_ID) INTO V_MAX_DEPTNO
    FROM DEPARTMENTS;
    
    V_DEPT_ID := V_MAX_DEPTNO + 10;
    
    INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
    VALUES (V_DEPT_ID, V_DEPT_NAME, NULL);
    
    DBMS_OUTPUT.PUT_LINE('The Maximun Department_ID is : ' || V_MAX_DEPTNO);
    DBMS_OUTPUT.PUT_LINE('SQL%ROWCOUNT GIVES ' || SQL%ROWCOUNT);
END;
/

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 200;


-- PRACTICE 3
BEGIN
    UPDATE DEPARTMENTS
    SET LOCATION_ID = 3000
    WHERE DEPARTMENT_ID = 200;
END;
/

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 200;

DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 200;