-- practice 1
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000
ORDER BY SALARY DESC, LAST_NAME DESC;

-- practice 2
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

-- practice 3
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000
ORDER BY SALARY DESC, LAST_NAME DESC;

-- practice 4
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'Matos' 
   OR LAST_NAME = 'Taylor'
ORDER BY HIRE_DATE;

-- practice 5
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20, 50)
ORDER BY LAST_NAME;

-- practice 6
SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary"
FROM EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) 
  AND DEPARTMENT_ID IN (20, 50)
ORDER BY SALARY DESC, LAST_NAME DESC;

-- practice 7
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '2006/01/01' 
            AND TO_DATE('2007/01/01') - 1/86400;
            
-- practice 8
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- practice 9
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC, COMMISSION_PCT DESC;

-- practice 10
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > &SET_SALARY
ORDER BY SALARY DESC;

-- practice 11
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = &SET_MANAGER_ID
ORDER BY &ORDER;

-- practice 12
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%'
ORDER BY LAST_NAME;

-- practice 13
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%'
  AND LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME;

-- practice 14
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP', 'ST_CLERK') 
  AND SALARY NOT IN (2500, 3500, 7000);

-- practice 15
SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary", COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT = 0.2
ORDER BY SALARY DESC, LAST_NAME DESC;